### ISSUE TITLE
Instagram have argument `response_type`

### ISSUE THREAD

**Issue by drozdzynski** [kanekotic/oauth-electron#2]
Hello,

I can't use your library with **Instagram** because it requires argument `response_type`:
```
https://api.instagram.com/oauth/authorize/?client_id=___&redirect_uri=http://localhost&response_type=code&scope=public_content
```

**Comment by alvarolorentedev** [comment]
@drozdzynski thanks for opening an issue. I will check this as soon as I have a minute. What is this parameter used for?

**Comment by drozdzynski** [comment]
[Here](https://www.instagram.com/developer/authentication/) you can find more info.

**Comment by schuster19uk** [comment]
Many places require response_type I need this for mixer.com.

**Comment by alvarolorentedev** [comment]
Y added this today and released 1.1.0, let me know if it works or you have any other issue :) . Thanks for spoting this @drozdzynski and @schuster19uk

**Comment by schuster19uk** [comment]
Whilst this has fixed the requirement for response_type , my promises aren't resolving. 

I am using the following config:

   let streamerScopes = "user:details:self chat:connect chat:chat chat:whisper chat:bypass_links chat:bypass_slowchat chat:bypass_catbot chat:bypass_filter chat:clear_messages chat:giveaway_start chat:poll_start chat:remove_message chat:timeout chat:view_deleted chat:purge channel:details:self channel:update:self channel:clip:create:self";

    let info = {
        key: '5ca546b27d464fc8e8fc8ac42e38380c5917710bbdf9545d',
        scope: streamerScopes,
        baseSite: "",
        authorizePath: "https://mixer.com/oauth/authorize",
        accessTokenPath: "https://mixer.com/api/v1/oauth/token",
        redirectUrl: "http://localhost:8081/auth/mixer2",
        response_type: "token"
    };


    loginAuth.oauth2(info, loginWindow).then(token => {
        console.log(token);
    }).catch(err => {
        console.log("error");
    }); 

@kanekotic

**Comment by alvarolorentedev** [comment]
so the event I am using has been deprecated in latest versions of electron i am looking for the alternative (`did-get-redirect-request`), are you using v3 of electron?

**Comment by alvarolorentedev** [comment]
I will close this and open a different issue

**Comment by alvarolorentedev** [comment]
#3
